name: CampWarspv2
version: '${project.version}'
main: me.logan.campwarspv2.Main
api-version: 1.20
authors: [ Logan ]
description: Updated / customisable camp warps plugin
commands:
  camp:
    aliases: Camps, Camp, camps
  setcamp:
  delcamp:
